version: '3.3'
volumes:
  shib-socket:

services:
  carriage:
    container_name: carriage
    build:
      context: .
      args:
        REACT_APP_PUBLIC_VAPID_KEY: BKH
    volumes:
      - .env:/usr/src/app/server/.env:ro
      - .env:/usr/src/app/.env:ro
    environment:
      PORT: 8080
      AWS_REGION: us-east-1
      DYNAMODB_URL: "http://dynamodb:8000"
      CREATE_DYNAMO_TABLES: "true"
      AWS_ACCESS_KEY_ID: AKIA
      AWS_SECRET_ACCESS_KEY: WZfnDtgb
      WEB_PUSH_CONTACT: "mailto:wm284@cornell.edu"

    links:
      - dynamodb



  # this nginx is an SSL terminator; the only purpose is to give you ssl;
  # it acts like an aws carriagelication load balancer.
  nginx:
    ports:
      - 80:80
      - 443:443
    image: ployst/nginx-ssl-proxy
    environment:
      ENABLE_SSL: "true"
      # TARGET_SERVICE: nginx-shib
      TARGET_SERVICE: "carriage:8080"
      
      SERVER_NAME: carriage.local
    volumes:
      - ./nginx-certs/certs/keyfile.crt:/etc/secrets/proxycert
      - ./nginx-certs/certs/keyfile.key:/etc/secrets/proxykey
      - ./nginx-certs/certs/dhparam.pem:/etc/secrets/dhparam
    links:
      - carriage
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    volumes:
      - "./tmp/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    ports:
      - 8000:8000

# This is left as a TODO.  Container exists, but isn't ready for production.
#   apache-shib:
#     env_file: .env
#     image: apache-shib
#     container_name: apache-shib
#     build: ./apache-shib
#     environment:
#     - SET_CONTAINER_TIMEZONE=true
#     - TZ=America/New_York
#     volumes:
#     - ./apache-shib/logs/apache2:/var/log/apache2
#     - ./apache-shib/logs/shib:/var/log/shibboleth
#     # Sync time from host:
#     - /etc/localtime:/etc/localtime:ro
#     - ${PHP_carriage_PATH}:/carriage
#     ports:
#     - 90:80
#   - 543:443
